### ISSUE TITLE
JEP 248: Make G1 the Default Garbage Collector

### ISSUE THREAD

**Issue by jabrena** [jabrena/java9-by-example#4]
https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-1F270BDA-50B0-49C8-807E-0B727CCC5169

**Comment by jabrena** [comment]
https://www.azul.com/products/zing/pgc/

**Comment by jabrena** [comment]
https://es.slideshare.net/mobile/MonicaBeckwith/java-9-the-g1-gc-awakens

**Comment by juan-medina** [comment]
https://docs.oracle.com/javase/9/gctuning/garbage-first-garbage-collector.htm#JSGCT-GUID-ED3AB6D3-FD9B-4447-9EDF-983ED2F7A573

**Comment by juan-medina** [comment]
https://www.infoq.com/articles/G1-One-Garbage-Collector-To-Rule-Them-All

**Comment by juan-medina** [comment]
https://www.infoq.com/articles/Make-G1-Default-Garbage-Collector-in-Java-9

**Comment by juan-medina** [comment]
http://openjdk.java.net/jeps/271

**Comment by jabrena** [comment]
Fixed
